 /* Classic Models has a product line called "Vintage Cars." 
The management wants to know the total revenue generated by
 this product line in the last quarter of the year 2003 (from October to December). 
 Write a MySQL stored procedure that takes no input parameters and 
 returns total revenue of the "Vintage Cars" product line for the last quarter of 2003. */
 use classicmodels;
Delimiter $$

CREATE PROCEDURE VintageCarTotalRevenue()
BEGIN
    
    SELECT SUM(ord.priceEach * ord.quantityOrdered) as totalrevenue
    FROM orderdetails ord
    JOIN orders o ON ord.orderNumber = o.orderNumber
    WHERE o.orderDate BETWEEN '2003-10-01' AND '2003-12-31'
    AND ord.productCode IN (SELECT productCode FROM products WHERE productLine = 'Vintage Cars');
    
    SELECT totalrevenue;
END $$

call VintageCarTotalRevenue();




